name: Merge EPG Data

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC (8:00 AM GMT+8)
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Run Pluto Data Script
      run: php php/grab_pluto_data.php
      continue-on-error: true

    - name: List Files in Pluto-TV Directory
      run: ls -l Pluto-TV

    - name: Add generated files to Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Pluto-TV/us.m3u8 Pluto-TV/us.xml
        git commit -m "Update Pluto TV EPG and playlist" || echo "No changes"
        git pull --rebase origin main || true
        git push

    - name: Run PHP Script
      env:
        GAS_KEY: ${{ secrets.GAS_KEY }}
      run: php php/mergeEpgs.php
